export const programs = [
  {
    id: 'handstand-free',
    name: 'Free Handstand Beginner Guide',
    emoji: '🤸',
    thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=400&fit=crop',
    tag: 'FREE',
    tagColor: 'text-green-400 bg-green-400/15',
    available: true,
    locked: false,
    for: 'Beginners with zero handstand experience',
    skill: 'Handstand',
    description: 'Learn to kick up, balance, and build your first freestanding handstand from scratch.',
    includes: ['Wall conditioning drills', 'Kick-up technique', 'Balance progressions', 'Freestanding hold training'],
    to: '/tutorials/handstand',
    cta: 'Start Free',
  },
  {
    id: 'planche-free',
    name: 'Free Planche Conditioning',
    emoji: '💪',
    thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop',
    tag: 'FREE',
    tagColor: 'text-green-400 bg-green-400/15',
    available: true,
    locked: false,
    for: 'Athletes building straight-arm strength',
    skill: 'Planche',
    description: 'Build the wrist, scapula, and straight-arm strength required for planche progressions.',
    includes: ['Wrist preparation', 'Scapula conditioning', 'Pseudo planche pushups', 'Planche lean protocol'],
    to: '/tutorials/planche',
    cta: 'Start Free',
  },
  {
    id: 'planche-program',
    name: 'Planche Program',
    emoji: '🏆',
    thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop',
    tag: 'COMING SOON',
    tagColor: 'text-amber-400 bg-amber-400/15',
    available: false,
    locked: true,
    for: 'Athletes who can hold a tuck planche',
    skill: 'Planche',
    description: 'Full structured planche program from tuck to full planche. Periodized, tested, elite.',
    includes: ['12-week periodized plan', 'Tuck → Straddle → Full roadmap', 'Video breakdowns', 'Weekly check-in structure'],
    to: '/apply',
    cta: 'Apply for 1-on-1 Coaching',
  },
  {
    id: 'frontlever-program',
    name: 'Front Lever Program',
    emoji: '⚡',
    thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=400&fit=crop',
    tag: 'COMING SOON',
    tagColor: 'text-amber-400 bg-amber-400/15',
    available: false,
    locked: true,
    for: 'Athletes with 10+ strict pullups',
    skill: 'Front Lever',
    description: 'Structured front lever program from tuck progressions to full front lever holds.',
    includes: ['Progressive tuck → full FL', 'Ice cream makers', 'Front lever rows', 'Negatives protocol'],
    to: '/apply',
    cta: 'Apply for 1-on-1 Coaching',
  },
  {
    id: 'muscleup-program',
    name: 'Muscle-Up Program',
    emoji: '🔥',
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop',
    tag: 'COMING SOON',
    tagColor: 'text-amber-400 bg-amber-400/15',
    available: false,
    locked: true,
    for: 'Athletes with 8+ clean pullups',
    skill: 'Muscle-Up',
    description: 'Go from high pullups to strict chest-to-bar and clean muscle-up repetitions.',
    includes: ['Transition skill training', 'False grip conditioning', 'Band-assisted progressions', 'Strict MU protocol'],
    to: '/apply',
    cta: 'Apply for 1-on-1 Coaching',
  },
  {
    id: 'hspu-program',
    name: 'HSPU Program',
    emoji: '🎯',
    thumbnail: 'https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?w=600&h=400&fit=crop',
    tag: 'COMING SOON',
    tagColor: 'text-amber-400 bg-amber-400/15',
    available: false,
    locked: true,
    for: 'Athletes with 10+ second handstand holds',
    skill: 'HSPU',
    description: 'Progress from pike pushups and wall HSPU to freestanding handstand pushups.',
    includes: ['Pike pushup protocol', 'Wall HSPU progressions', 'Bent arm press training', 'Freestanding HSPU pathway'],
    to: '/apply',
    cta: 'Apply for 1-on-1 Coaching',
  },
  {
    id: 'coaching-1on1',
    name: '1-on-1 Coaching',
    emoji: '👁️',
    thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=400&fit=crop',
    tag: 'AVAILABLE NOW',
    tagColor: 'text-primary bg-primary/15',
    available: true,
    locked: false,
    featured: true,
    for: 'Serious athletes ready to fast-track results',
    skill: 'All Skills',
    description: 'Direct coaching from BTCALI. Custom programs, video feedback, and weekly strategy. While full programs are being built — 1-on-1 coaching is how serious athletes get results now.',
    includes: ['Custom periodized program', 'Weekly video feedback', 'Direct coach messaging', 'Athlete progress tracking', 'Flexible skill focus'],
    to: '/apply',
    cta: 'Apply for Coaching',
  },
];