export const programs = [
  {
    id: 'handstand-free',
    name: 'Free Handstand Beginner Guide',
    emoji: '🤸',
    thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=400&fit=crop',
    tag: 'FREE',
    tagColor: 'text-green-400 bg-green-400/15',
    available: true,
    locked: false,
    for: 'Beginners with zero handstand experience',
    skill: 'Handstand',
    description: 'Learn to kick up, balance, and build your first freestanding handstand from scratch.',
    includes: ['Wall conditioning drills', 'Kick-up technique', 'Balance progressions', 'Freestanding hold training'],
    to: '/tutorials/handstand',
    cta: 'Start Free',
  },
  {
    id: 'handstand-program',
    name: 'Handstand Program',
    emoji: '🤸‍♂️',
    thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-primary bg-primary/15',
    available: false,
    locked: true,
    for: 'Athletes with basic kick-up ability',
    skill: 'Handstand',
    description: 'Full structured 12-week handstand program from freestanding holds to HSPU and walking.',
    includes: ['12-week periodized plan', 'Freestanding → HSPU pathway', 'Video breakdowns per phase', 'One-arm handstand prep'],
    to: '/purchase?type=handstand',
    cta: 'Get Access',
  },
  {
    id: 'planche-free',
    name: 'Free Planche Conditioning',
    emoji: '💪',
    thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop',
    tag: 'FREE',
    tagColor: 'text-green-400 bg-green-400/15',
    available: true,
    locked: false,
    for: 'Athletes building straight-arm strength',
    skill: 'Planche',
    description: 'Build the wrist, scapula, and straight-arm strength required for planche progressions.',
    includes: ['Wrist preparation', 'Scapula conditioning', 'Pseudo planche pushups', 'Planche lean protocol'],
    to: '/tutorials/planche',
    cta: 'Start Free',
  },
  {
    id: 'planche-program',
    name: 'Planche Program',
    emoji: '🏆',
    thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop',
    tag: 'COMING SOON',
    tagColor: 'text-amber-400 bg-amber-400/15',
    available: false,
    locked: true,
    for: 'Athletes who can hold a tuck planche',
    skill: 'Planche',
    description: 'Full structured planche program from tuck to full planche. Periodized, tested, elite.',
    includes: ['12-week periodized plan', 'Tuck → Straddle → Full roadmap', 'Video breakdowns', 'Weekly check-in structure'],
    to: '/apply',
    cta: 'Apply for 1-on-1 Coaching',
  },
  {
    id: 'frontlever-v1',
    name: 'Front Lever V1',
    emoji: '⚡',
    thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 5–10 pullups',
    skill: 'Front Lever',
    description: 'Build your tuck front lever and start developing horizontal pulling strength.',
    requirements: ['5–10 clean pullups'],
    includes: ['Tuck FL holds & progressions', 'Ice cream maker introduction', 'Lat activation protocols', 'Core horizontal strength', 'Goal: 10 sec tuck FL, 3 sec adv tuck'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-v2',
    name: 'Front Lever V2',
    emoji: '🔱',
    thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 10 pullups and 3 sec adv tuck',
    skill: 'Front Lever',
    description: 'Develop advanced tuck endurance and begin purple band full front lever work.',
    requirements: ['10 clean pullups', '3 sec advanced tuck FL'],
    includes: ['Advanced tuck FL endurance', 'Purple band FL progressions', 'Front lever rows', 'Scapular retraction strength', 'Goal: 5 sec adv tuck, 5 sec purple band FL'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-v3',
    name: 'Front Lever V3',
    emoji: '💎',
    thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 5 sec adv tuck and 5 sec purple band FL',
    skill: 'Front Lever',
    description: 'Progress to black band and build serious full FL holding capacity.',
    requirements: ['5 sec advanced tuck FL', '5 sec purple band FL'],
    includes: ['Black band FL progression', 'Advanced tuck to 10 sec', 'FL row volume building', 'Periodized pulling cycles', 'Goal: 5 sec black band FL, 10 sec adv tuck'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-v4',
    name: 'Front Lever V4',
    emoji: '🏅',
    thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 5 sec black band and 10 sec adv tuck FL',
    skill: 'Front Lever',
    description: 'Transition to red band and build FL raises for full FL strength.',
    requirements: ['5 sec black band FL', '10 sec advanced tuck FL'],
    includes: ['Red band FL progressions', '10 sec black band hold', 'Black band FL raises', 'Intensity periodization', 'Goal: 3–5 sec red band FL, 10 sec black band'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-v5',
    name: 'Front Lever V5',
    emoji: '🌟',
    thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 3–5 sec red band FL',
    skill: 'Front Lever',
    description: 'Build red band endurance and FL raises for full front lever development.',
    requirements: ['3–5 sec red band FL'],
    includes: ['Red band hold endurance to 10 sec', 'FL raises introduction', 'Max effort FL attempts', 'Pulling strength cycles', 'Goal: 10 sec red band FL, FL raises'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-v6',
    name: 'Front Lever V6',
    emoji: '👑',
    thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 10 sec red band FL',
    skill: 'Front Lever',
    description: 'Unlock the full front lever — the pinnacle of horizontal pulling strength.',
    requirements: ['10 sec red band FL'],
    includes: ['Full FL first attempts', 'Advanced FL raises', 'FL rowing variations', 'Peak strength cycles', 'Goal: 3–5 sec full front lever'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'muscleup-program',
    name: 'Muscle-Up Program',
    emoji: '🔥',
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop',
    tag: 'COMING SOON',
    tagColor: 'text-amber-400 bg-amber-400/15',
    available: false,
    locked: true,
    for: 'Athletes with 8+ clean pullups',
    skill: 'Muscle-Up',
    description: 'Go from high pullups to strict chest-to-bar and clean muscle-up repetitions.',
    includes: ['Transition skill training', 'False grip conditioning', 'Band-assisted progressions', 'Strict MU protocol'],
    to: '/purchase?type=coaching',
    cta: 'View Program Details',
  },
  {
    id: 'hspu-program',
    name: 'HSPU Program',
    emoji: '🎯',
    thumbnail: 'https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?w=600&h=400&fit=crop',
    tag: 'COMING SOON',
    tagColor: 'text-amber-400 bg-amber-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 10+ second handstand holds',
    skill: 'HSPU',
    description: 'Progress from pike pushups and wall HSPU to freestanding handstand pushups.',
    includes: ['Pike pushup protocol', 'Wall HSPU progressions', 'Bent arm press training', 'Freestanding HSPU pathway'],
    to: '/purchase?type=coaching',
    cta: 'View Program Details',
  },
  {
    id: 'coaching-1on1',
    name: '1-on-1 Coaching',
    emoji: '👁️',
    thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=400&fit=crop',
    tag: 'AVAILABLE NOW',
    tagColor: 'text-primary bg-primary/15',
    available: true,
    locked: false,
    featured: true,
    for: 'Serious athletes ready to fast-track results',
    skill: 'All Skills',
    description: 'Direct coaching from BTCALI. Custom programs, video feedback, and weekly strategy. While full programs are being built — 1-on-1 coaching is how serious athletes get results now.',
    includes: ['Custom periodized program', 'Weekly video feedback', 'Direct coach messaging', 'Athlete progress tracking', 'Flexible skill focus'],
    to: '/purchase?type=coaching',
    cta: 'Apply for Coaching',
  },
];