// All student programs — exact data from BTCALI Google Sheets
// Used for initial seeding only. Live data is stored in StudentProgram entity.

function row(activity, rep_range, exercise_type, notes = '', tutorial_link = '') {
  return { id: Math.random().toString(36).slice(2), activity, rep_range, exercise_type, notes, tutorial_link };
}
function tab(name, rows) {
  return { id: Math.random().toString(36).slice(2), name, rows };
}

export const STUDENT_PROGRAMS = [
  {
    access_code: 'HENRY173', student_name: 'Henry',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Bent arm tuck planche raises', 'As many as you can, 2 sets', 'volume / intensity', '', ''),
        row('Wall HSPU max', '2 sets', 'volume / intensity', '', ''),
        row('Decline pike pushup max', '2 sets', 'volume / intensity', '', ''),
        row('Pike pushup', 'Max amount 2 sets', 'volume / intensity', '', ''),
        row('Handstand attempts (Only once you know how to bail)', 'As many sets as you can and have time for', 'attempt', '', ''),
        row('Chest to wall handstand toe taps', '2 sets as long as you can', 'technique', '', ''),
        row('Max dips', '2 sets', 'conditioning', '', ''),
        row('Scapular pushups to normal pushups', '10 reps 1 set', 'technique', '', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep range', 'warmup', '', ''),
        row('L sit', '2 sets, as long as you can', 'volume / intensity', '', ''),
        row('Bent knee L sit', '2 sets as long as you can', 'volume', '', ''),
        row('Floor L sit raises', '5-8 reps, 2 sets', 'volume', '', ''),
        row('Max pullups', '2 sets', 'volume / intensity', '', ''),
        row('Max half ROM pullups (Bottom ROM)', '2 sets', 'volume / intensity', '', ''),
        row('Max half ROM pullups (Top ROM)', '2 sets', 'volume / intensity', '', ''),
      ]),
    ],
  },
  {
    access_code: 'HAEJUN142', student_name: 'Haejun',
    tabs: [
      tab('Pull', [
        row('Warmup', 'Reps and sets', 'warmup', '', ''),
        row('Full front lever attempt', '2 set', 'attempt', '', ''),
        row('Half red band Full FL hold', '2 sets', 'volume / intensity', '', ''),
        row('Half red band Full FL raises', '2 sets', 'volume / intensity', '', ''),
        row('Red band assisted front lever', '2 sets', 'volume / intensity', '', ''),
        row('Red band assisted FL raises', '2 sets', 'volume / intensity', 'Do hold, then raise, then hold, then raise, then hold', ''),
        row('Adv tuck', '2 sets', 'volume', '', ''),
        row('Weighted pullup 2-3 rep range', '2 sets', 'basics', '', ''),
        row('Weighted pullup 3-5 reps', '2 sets', 'basics', '', ''),
        row('Weighted pullup 5-8 rep', '2 sets', 'basics', '', ''),
        row('max Normal pullups', '1 set till failure', 'basics', '', ''),
      ]),
      tab('Push', [
        row('Handstand pushup attempts', '3 sets', 'attempt', 'Move onto next exercise once fatigued', ''),
        row('Bent arm press max', 'As many as you can, 2 sets', 'volume / intensity', 'Try to control it from the handstand, if you fall down just spam bent arm press until its physically too hard', ''),
        row('Max handstand pushups on wall. Pike pushup lift ups x2', 'As many as you can, 2 sets', 'volume / intensity', 'Do as many as you can chest to wall, ideally slippery wall and slippery socks, if not thats fine', ''),
        row('90 degree hold attempt', '1 set', 'attempt', '', ''),
        row('90 degree toe taps', '1 set', 'attempt', '', ''),
        row('90 degree lift offs', '1 set', 'attempt', '', ''),
        row('Pseudo planche hold', '3-4 sets', 'volume / intensity', 'Lean forward as much as you can while constantly pushing off the floor', ''),
        row('Max handstand hold', 'as many seconds as you can approx 2 sets', 'basics', 'Good for mastering handstand foundation', ''),
        row('Handstand chest to wall toe taps', 'as long as you can', 'basics', 'Essential for learning how to balance', ''),
        row('Weighted dips 5-8 rep', '3-4 sets', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'ANDREAS189', student_name: 'Andreas',
    tabs: [
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('Full front lever attempt', '2 set', 'attempt', '', ''),
        row('Half red band assisted full FL', '2 sets', 'volume / intensity', '', ''),
        row('Half red band assisted full FL raises', '2 sets', 'volume / intensity', '', ''),
        row('red band assisted full FL', '2 sets', 'volume / intensity', '', ''),
        row('red band assisted full FL raises', '2 sets', 'volume / intensity', '', ''),
        row('FL hip thrusts', '2 sets', 'technique', '', ''),
        row('FL deadlifts', '1 set', 'technique', '', ''),
      ]),
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Do your normal warm-up, some light HSPU as well just to get shoulders warmed up', 'Rep range', 'warmup', 'Message me if you need any tips but im pretty sure you can know how to do this easily', ''),
        row('Straddle planche attempt', '2 sets', 'attempt', '', ''),
        row('Adv tuck attempt', '2 sets', 'volume / intensity', '', ''),
        row('Bent arm press attempt', '3 sets', 'volume / intensity', '', ''),
        row('wall HSPU max', '2 sets', 'volume / intensity', '', ''),
        row('Dolphin presses', 'not really specific rep range but just get familiar with the movement', 'conditioning', 'Engage super hard through serratus, same activations as pseudo lean but mostly focusing on the serratus, external rotation, chin, PPT, core engagements', ''),
        row('Planche lean', 'not specific set, just get familiar with the movement and engagements', 'conditioning', 'Really work on correct activations: PPT, engage core, chin slightly forward, press through serratus, externally rotate, breathing, pointed toes', ''),
        row('Planche presses', 'not specific set, just get familiar with the movement and engagements', 'conditioning', '', ''),
        row("Zanneti's", '5-8 rep range, 1-2 sets', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'TANUSH157', student_name: 'Tanush',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Bent arm tuck planche raises', 'As many as you can, 2 sets', 'attempt', "I need to include proper tutorial explaining, but here is basically the position I want you to get into, just raise into it :) Don't kick off", ''),
        row('Pike pushup attempt', 'Max amount 3 sets', 'volume / intensity', '', ''),
        row('Bent knee pike push-ups', 'As many as you can do, 2 sets', 'volume / intensity', '', ''),
        row('Max Dips good form', '2 sets', 'conditioning', '', ''),
        row('Handstand attempts', '2 sets', 'conditioning', '', ''),
        row('Handstand hold chest to wall', '1 set', 'conditioning', '', ''),
        row('Scapular pushups to normal pushups', '10 reps 1 set', 'conditioning', 'I want to familiarise you with protraction and retraction, essential for the future', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('Purple banded Full FL max hold', '1 set', 'volume / intensity', '', ''),
        row('Green banded Full FL', '2 sets', 'volume / intensity', '', ''),
        row('Front lever hip thrust', '1 set green band', 'technique', '', ''),
        row('Front lever deadlifts', '1 set green band', 'technique', '', ''),
        row('L sit attempt', '1 set', 'attempt', '', ''),
        row('L sit with one leg', '2 sets', 'volume', '', ''),
        row('Bent knee L sit', '2 sets as long as you can', 'volume', '', ''),
        row('Max L sit raises', '2 sets', 'volume', '', ''),
        row('Max pullups', '5 sets', 'conditioning', '', ''),
        row('Max pull-up hold, hold at top ROM', '1 set', 'basics', 'Getting familiar in top ROM', ''),
        row('Max scapular pullups', '1 set', 'basics', '', ''),
        row('Max chin ups', '1 set', 'basics', '', ''),
        row('Standing Bicep curls Supinated', '6-8 reps 2 sets', 'basics', '', ''),
        row('Standing Bicep curls neutral grip', '6-8 reps 2 sets', 'basics', '', ''),
      ]),
    ],
  },
  {
    access_code: 'RYAN128', student_name: 'Ryan',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Set range', 'warmup', '', ''),
        row('L sit to handstand on P bars', '1 set, as many as you can do in one set', 'attempt', '', ''),
        row('Clean bent arm press attempt (Start with no momentum)', '2 sets, as many as you can do in one set', 'attempt', '', ''),
        row('Bent arm press attempts', '3 sets, as many as you can do in one set', 'attempt', '', ''),
        row('Chest to wall handstand pushups max', '3 sets', 'volume / intensity', '', ''),
        row('Decline pike pushup max reps', '2 sets', 'volume / intensity', 'Rest your legs on top of a chair or couch', ''),
        row('Handstand holds', '2 sets, as many as you can do in one set', 'conditioning', '', ''),
        row('Handstand chest to wall toe taps', '2 sets, as many as you can do in one set', 'conditioning', '', ''),
        row('Back to wall handstand attempts', '2 sets', 'conditioning', '', ''),
        row('Dips', 'max 1 set', 'conditioning', '', ''),
        row('Scapular pushups to normal pushups', '10 reps 1 set', 'conditioning', 'I want to familiarise you with protraction and retraction, essential for the future', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('Black and red FL max', '2 sets', 'volume / intensity', '', ''),
        row('Adv tuck FL attempt max', '1 set', 'volume / intensity', '', ''),
        row('Tuck front lever max', '2 sets, as long as you can with good horizontal form', 'volume / intensity', '', ''),
        row('Super heavy banded FL hip thrusts max good form', '1 set', 'conditioning', '', ''),
        row('High pullup attempt', '1 set', 'attempt', '', ''),
        row('Max pullups', '3-4 sets', 'conditioning', 'Grease the groove', ''),
        row('Pullups Top ROM (I will explain to you)', '1 set', 'conditioning', '', ''),
        row('L sit max', '1 set', 'conditioning', '', ''),
        row('Elevated L sit (P bars)', '2 sets', 'conditioning', '', ''),
        row('Tuck L sit (P bars)', '2 sets', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'JULIAN194', student_name: 'Julian',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Bent arm press attempts', '2 sets, 2-3 reps of attempts', 'attempt', '', ''),
        row('Bent arm tuck planche raises', 'As many as you can, 2 sets', 'volume / intensity', 'Raise into the hardest position you can for reps', ''),
        row('Chest to wall HSPU', '2 sets', 'volume / intensity', '', ''),
        row('Decline pike pushup max', '2 sets', 'volume / intensity', '', ''),
        row('Pike pushup', 'Max amount 2 sets', 'volume / intensity', '', ''),
        row('Dips', '1-2 sets max', 'technique', '', ''),
        row('Handstand attempts', '2 sets', 'technique', '', ''),
        row('Chest to wall handstand toe taps', '3 sets as long as you can', 'basics', '', ''),
        row('Scapular pushups to normal pushups', '10 reps 1 set', 'basics', '', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('Banded full FL hold Blue band', '2 set', 'attempt', 'I just wanna see what level your at right now', ''),
        row('Banded full FL raises Blue band', '1 set', 'attempt', '', ''),
        row('Yellow Banded full FL hold', '2 sets', 'volume / intensity', 'Attach band my method', ''),
        row('Yellow Banded full FL raises max', '2 set', 'volume / intensity', '', ''),
        row('Orange banded max hold', '1 set', 'volume / intensity', '', ''),
        row('Orange banded max raises', '1 set', 'volume / intensity', '', ''),
        row('Max adv tuck lever', '1 set', 'volume', '', ''),
        row('FL hip thrust (Super heavy band)', '2 set', 'technique', 'You can attach more than one band', ''),
        row('FL deadlifts (Heavy band)', '2 set', 'technique', '', ''),
        row('Max pullups (If you have a bar)', '1 set', 'conditioning', '', ''),
        row('Max L sit', '1 set', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'MACK136', student_name: 'Mack',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Max Pike pushup attempt', '3 sets', 'attempt', '', ''),
        row('Bent knee pike push-ups', '2 sets', 'volume / intensity', '', ''),
        row('max dips', '2 sets', 'volume / intensity', '', ''),
        row('Handstand attempts (Multiple in one set)', '2 sets', 'technique', '', ''),
        row('Handstand back to wall', '2 sets', 'technique', '', ''),
        row('Handstand toe taps (Multiple in one set)', '2 sets', 'technique', '', ''),
        row('Gym work', 'Rep range', 'conditioning', '', ''),
        row('Scapular pushups to normal pushups (Do this after all your gym work)', '10 reps 1 set', 'conditioning', '', ''),
        row('Max pushups', '1 set', 'conditioning', '', ''),
        row('where to look in handstand', 'tutorial link', '', '', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('5 kg pullup', '2 sets', 'attempt', '', ''),
        row('Max pullups', '3 sets', 'volume / intensity', '', ''),
        row('Max pullups (top ROM partial reps)', '2 sets', 'volume', '', ''),
        row('Max Pullup hold (Hold at the top)', '1 set', 'volume', '', ''),
        row('L sit on chairs (Or elevated surface)', '2 sets', 'attempt', '', ''),
        row('Elevated Bent knee L sit', '3 sets as long as you can', 'volume / intensity', '', ''),
        row('L sit compression hold', '2 sets', 'volume', '', ''),
        row('L sit compression raises', '2 set', 'volume', '', ''),
        row('Max L sit raises', '2 sets', 'volume', '', ''),
      ]),
    ],
  },
  {
    access_code: 'MARCUS181', student_name: 'Marcus',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Do your normal warm-up, some light HSPU as well just do get shoulders warmed up', 'Rep range', 'warmup', 'Message me if you need any tips but im pretty sure you can know how to do this easily', ''),
        row('Full planche', '1 set', 'attempt', '', ''),
        row('Straddle attempt', '2 sets', 'attempt', 'max straddle planche hold, aim for as perfect form as possible, PPT, toes pointed, i will show you how to enter with my strat.', ''),
        row('Max straddle press', '2 sets', 'volume / intensity', '', ''),
        row('Max straddle, dropset into adv tuck, rest 5 sec', '2 set', 'volume / intensity', '', ''),
        row('Max adv tuck hold', '2 sets', 'volume / intensity', 'Max straddle hold, dropsetted to max adv tuck hold. You can rest up to 5 seconds and catch your breathe between the holds', ''),
        row('2x banded straddle press', '2-3 rep range', 'volume / intensity', '', ''),
        row('2x banded straddle pushup to hold', '3 to hold', 'conditioning', '', ''),
        row('supinated adv tuck planche (Floor)', '2 sets', 'conditioning', 'good for height', ''),
        row('P bar HSPU', '2 sets', 'volume', 'depending how tired you are', ''),
        row('Wall HSPU max (Deeppppp)', '2 sets', 'volume', '', ''),
        row('Dolphin presses', 'not really specific rep range but just get familiar with the movement', 'conditioning', 'Engage super hard through serratus, same activations as pseudo lean but mostly focusing on the serratus, external rotation, chin, PPT, core engagements', ''),
        row('Planche lean', 'not specific set, just get familiar with the movement and engagements', 'conditioning', 'Really work on the correct activations: PPT, engage core, chin slightly forward, press through serratus, externally rotate, breathing, pointed toes', ''),
        row('Planche presses', 'not specific set, just get familiar with the movement and engagements', 'conditioning', '', ''),
        row("Zanneti's", '5-8 rep range, 1-2 sets', 'conditioning', '', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('red band assisted full FL', '3 set', 'attempt', '', ''),
        row('red band raise attempt', '2 set', 'attempt', '', ''),
        row('black band assisted full FL', '3 sets', 'volume / intensity', '', ''),
        row('Black band assisted full FL raises', '2 sets', 'volume / intensity', '', ''),
        row('Adv tuck FL', '2 sets', 'volume', '', ''),
        row('FL hip thrusts', '2 sets', 'technique', '', ''),
        row('FL deadlifts', '2 set', 'technique', '', ''),
      ]),
    ],
  },
  {
    access_code: 'ALISTAIR149', student_name: 'Alistair',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('HSPU attempt', '2 sets', 'attempt', '', ''),
        row('Bent arm press attempts', '4 sets, 2-3 reps of attempts', 'attempt', '', ''),
        row('Chest to wall handstand pushups', '3 sets max', 'volume / intensity', '', ''),
        row('Bent arm tuck planche raises', 'As many as you can, 3 sets', 'volume / intensity', 'Raise into the hardest position you can for reps', ''),
        row('Decline pike pushup max', '3 sets', 'volume / intensity', '', ''),
        row('Handstand attempts', '2 sets', 'attempt', '', ''),
        row('Handstand back to wall attempts', '2 sets', 'basics', '', ''),
        row('Chest to wall handstand toe taps', '3 sets as long as you can', 'basics', '', ''),
        row('Scapular pushups to normal pushups', '10 reps 1 set', 'basics', '', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('Banded full FL hold (3-5 sec range) Black band', '2 set', 'attempt', 'I just wanna see what level your at right now', ''),
        row('Banded full FL hold (5-8 sec range) purple', '2 sets', 'volume / intensity', 'Attach band my method', ''),
        row('Banded full FL raises max (3-5 rep range good form) purple', '2 set', 'volume / intensity', '', ''),
        row('Max adv tuck', '1 set', 'volume', '', ''),
        row('Max tuck FL', '1 set', 'volume', '', ''),
        row('FL hip thrust (Super heavy band)', '2 set', 'technique', 'You can attach more than one band', ''),
        row('FL deadlifts (Heavy band)', '2 set', 'technique', '', ''),
        row('Max pullups (If you have a bar)', '2 set', 'conditioning', '', ''),
        row('Max L sit', '1 sets', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'JAYDEN165', student_name: 'Jayden',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('L sit to handstand attempt', 'as many as you can do', 'attempt', 'really focus on putting your feet above your head and over balancing, kick and push at the same time', ''),
        row('bent arm press spam', 'as many as you can do', 'volume / intensity', "I don't expect you to hold this yet, just an attempt", ''),
        row('Chest to wall handstand pushups max', '2 sets', 'volume / intensity', '', ''),
        row('Decline pike pushup max reps', '2 sets', 'volume / intensity', 'Rest your legs ontop of a chair or couch, i am gonna send vid I am going to see if u can do this', ''),
        row('Handstand attempts', 'as many sets as you can and have energy/time for lol', 'basics', '', ''),
        row('Handstand chest to wall toe taps', '2 sets', 'basics', '', ''),
        row('Scapular pushups to normal pushups', '10 reps 1 set', 'basics', 'I want to familiarise you with protraction and retraction, essential for the future', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('Adv tuck FL attempt', '1 set', 'attempt', 'will teach you later', ''),
        row('Tuck front lever attempt', '2 sets, as long as you can with good horizontal form', 'volume / intensity', '', ''),
        row('L sit attempt', '2 sets, as long as you can', 'attempt', '', ''),
        row('Weighted pull-ups', '3-5 rep range 2 sets', 'basics', 'Only if you wanna build strength in weighted pull-ups', ''),
        row('Weighted pullups', '5-8 rep range 2 sets', 'basics', '', ''),
        row('Max pullups', '1 set', 'basics', '', ''),
      ]),
    ],
  },
  {
    access_code: 'LUKE121', student_name: 'Luke',
    tabs: [
      tab('Push', [
        row('warmup', 'rep range', 'warmup', '', ''),
        row('90 degree HSPU attempt', '1 set', 'attempt', '', ''),
        row('Other variations you would like to try (Optional)', '1 set', 'attempt', '', ''),
        row('HSPU attempt max', '3 sets', 'volume / intensity', '', ''),
        row('wall HSPU max', '2 sets', 'volume / intensity', '', ''),
        row('Max handstands', 'as many as you want, even GTG during the day', 'technique', '', ''),
        row('weighted dips', '4-5 reps 2 sets', 'conditioning', 'We will change once u get 5 reps for this weight', ''),
        row('weighted dips', '5-8 reps 2 sets (Optional)', 'conditioning', 'we will make weight higher once you hit 8', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', "I'm pretty sure you know how to warmup efficiently now, but lmk if you need any help", ''),
        row('Red band assisted hold', '1 set', 'attempt', '', ''),
        row('Black band assisted hold', '2 sets', 'volume / intensity', 'alternate', ''),
        row('Black band assisted raises', '2 sets', 'volume / intensity', 'alternate', ''),
        row('Purple band assisted hold', '2 sets', 'volume / intensity', 'Alternate', ''),
        row('Purple Band assisted FL raises', '2 sets', 'volume / intensity', 'Alternate', ''),
        row("FL thrust (Super heavy bands) Make sure to hold position, dont rush it", '1 set', 'technique', "Don't rush it, make sure when you get to a straight line you want to have a solid hold", ''),
        row('Banded Reverse deadlifts', '2 sets, really working on form, hold at the top', 'technique', "Don't rush it, make sure when you get to a straight line you want to have a solid hold", ''),
        row('Weighted pullups 3-5 rep range', '2 sets', 'conditioning', '', ''),
        row('Weighted pullups 5-8 rep range', '1-2 sets', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'GAON176', student_name: 'Gaon',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Bent arm press attempts', '3 sets as many as you can do in one set', 'attempt', '', ''),
        row('Bent arm tuck planche raises', 'As many as you can, 4 sets', 'volume / intensity', '', ''),
        row('Decline pike pushup max', '2 sets', 'volume / intensity', '', ''),
        row('Pike pushup', '2 sets', 'volume / intensity', '', ''),
        row('Handstand attempts', '3 sets', 'attempt', '', ''),
        row('Chest to wall handstand toe taps', '2 sets', 'basics', '', ''),
        row('Scapular pushups to normal pushups', '10 reps 1 set', 'basics', '', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('L sit attempt', '2 sets', 'attempt', '', ''),
        row('L sit with one leg', '2 sets', 'attempt', '', ''),
        row('Bent knee L sit', '2 sets as long as you can', 'volume / intensity', '', ''),
        row('Max normal pullups', '2 sets', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'DANIEL192', student_name: 'Daniel',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Bent arm press attempts', '5 sets as many as you can do in one set', 'attempt', '', ''),
        row('Bent arm tuck planche raises', 'As many as you can, 2 sets', 'volume / intensity', '', ''),
        row('Decline pike pushup max', '2 sets', 'volume / intensity', '', ''),
        row('Pike pushup', 'Max amount 2 sets', 'volume / intensity', '', ''),
        row('Handstand attempts (Only once you know how to bail)', 'As many sets as you can and have time for', 'attempt', '', ''),
        row('Chest to wall handstand toe taps', '3 sets as long as you can', 'technique', '', ''),
        row('Scapular pushups to normal pushups', '10 reps 1 set', 'technique', '', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('Banded Full FL', '3-5 sec range 2 sets', 'attempt', '', ''),
        row('Banded full FL', '5-8 sec range 2 sets', 'volume / intensity', '', ''),
        row('Adv tuck FL attempt', '3 sets', 'volume / intensity', '', ''),
        row('Tuck front lever', '2 sets', 'volume / intensity', '', ''),
        row('L sit', '2 sets, as long as you can', 'volume / intensity', '', ''),
        row('Bent knee L sit', '2 sets as long as you can', 'volume', '', ''),
        row('Weighted pull-ups', '1-3 rep range 2 sets', 'conditioning', '', ''),
        row('Weighted pullups', '5-8 rep range 2 sets', 'conditioning', '', ''),
        row('Max pullups', '1 set', 'conditioning', '', ''),
        row("Max pullups, into max partial reps, stop once arms are not going past 90 degree's", '1 set', 'conditioning', '', ''),
      ]),
      tab('Student Information', [
        row('Student information tab — add notes here', '', '', '', ''),
      ]),
    ],
  },
  {
    access_code: 'HAYDEN167', student_name: 'Hayden',
    tabs: [
      tab('Push V1', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Pike push-up attempt max', '1 set', 'attempt', "I don't expect you to be able to do this but it is good to attempt to see what level your at", ''),
        row('Bent Knee pike pushup max', 'Rep range', 'volume / intensity', '', ''),
        row("Push-up's max", 'Max amount of reps for 3 sets', 'volume / intensity', '', ''),
        row('Pushups to scapular pushups', '1 set 10 reps', 'volume / intensity', '', ''),
        row('Knee push-ups', 'Max amount of reps for 2 sets', 'volume / intensity', '', ''),
        row('Plank hold', 'Longest plank hold', 'conditioning', 'test how long you can hold that for', ''),
      ]),
      tab('Pull V1', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('L sit attempt', '2 sets, as long as you can', 'attempt', '', ''),
        row('Bent knee L sit', '2 sets as long as you can', 'attempt', '', ''),
        row('Max L sit raises', '1 set', 'volume / intensity', '', ''),
        row('Max pullups', '1-2 sets', 'volume / intensity', '', ''),
        row("Max pullups, into max partial reps, stop once arms are not going past 90 degree's", '1 set', 'volume / intensity', '', ''),
        row('Max pull-up hold, hold at top', '2 sets', 'volume / intensity', '', ''),
        row('Hollow body hold', '2 sets', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'HUGO144', student_name: 'Hugo',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Do your normal warm-up, some light HSPU as well just do get shoulders warmed up', 'Rep range', 'warmup', '', ''),
        row('90 degree HSPU attempt', '1 set', 'attempt', '', ''),
        row('Max adv tuck hold', '4 sets', 'volume / intensity', '', ''),
        row('90 degree HSPU', '2 sets', 'attempt', '', ''),
        row('Tuck planche (P bars)', '2 sets', 'volume / intensity', '', ''),
        row('floor tuck planche', '2 sets', 'conditioning', '', ''),
        row('Deep Wall HSPU max', '2 sets', 'volume', '', ''),
        row('Weighted dips 5-8 range', '2 sets', 'conditioning', '', ''),
        row('For the section below do every 1-2 days for conditioning :)', 'Rep range', '', '', ''),
        row('Dolphin presses', 'not really specific rep range but just get familiar with the movement', 'conditioning', '', ''),
        row('Planche lean', 'not specific set, just get familiar with the movement and engagements', 'conditioning', '', ''),
        row('Planche presses', 'not specific set, just get familiar with the movement and engagements', 'conditioning', '', ''),
        row("Zanneti's", '5-8 rep range, 1-2 sets', 'conditioning', '', ''),
        row('Wrist conditioning (I will make vids)', 'Rep range', '', '', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('Full FL attempt', '1 set', 'attempt', '', ''),
        row('red band assisted full FL', '3 sets', 'volume / intensity', '', ''),
        row('red band assisted full FL raises', '2 sets', 'volume / intensity', '', ''),
        row('black band assisted full FL', '2 sets', 'volume / intensity', '', ''),
        row('Black band assisted full FL raises', '2 sets', 'volume / intensity', '', ''),
        row('Adv tuck FL', '2 sets', 'volume', '', ''),
        row('FL hip thrusts', '2 sets', 'technique', '', ''),
        row('FL deadlifts', '1 set', 'technique', '', ''),
        row('Weighted pullups 3-5 rep range', '2 sets', 'conditioning', '', ''),
        row('Weighted pullups 5-8 rep range', '2 sets', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'CEDRICK185', student_name: 'Cedrick',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Full Planche attempt', '1 set', 'attempt', 'every sesh start with a max hold full planche, this will guage your strength for the session and also get crucial volume', ''),
        row('Max straddle hold', '2 sets', 'volume / intensity', 'max straddle planche hold, aim for as perfect form as possible, PPT, toes pointed, i will show you how to enter with my strat.', ''),
        row('Max super adv tuck hold', '1 set', 'volume / intensity', '', ''),
        row('Max adv tuck hold', '2 sets', 'volume / intensity', '', ''),
        row('2x deadstop straddle press', '2-3 rep range 2 sets', 'volume / intensity', '', ''),
        row('Banded Max straddle hold x1 set', '5-8 seconds, once you hit 8 seconds we will decrease band', 'volume', '', ''),
        row('supinated adv tuck planche (Floor)', '2 sets', 'conditioning', 'good for height', ''),
        row('2 sets max p bar HSPU', 'max', 'conditioning', 'depending how tired you are', ''),
        row('weighted dip program', 'Rep range', 'conditioning', '', ''),
        row('For the section below, you don\'t need to do every day, mostly just conditioning exercises to really learn the correct activations', 'Rep range', '', '', ''),
        row('Dolphin presses', 'not really specific rep range but just get familiar with the movement', 'conditioning', 'Engage super hard through serratus, same activations as pseudo lean but mostly focusing on the serratus, external rotation, chin, PPT, core', ''),
        row('Planche lean', 'not specific set, just get familiar with the movement and engagements', 'conditioning', 'Really work on the correct activations: PPT, engage core, chin slightly forward, press through serratus, externally rotate, breathing, pointed toes', ''),
        row('Planche lean presses', 'not specific set, just get familiar with the movement and engagements', 'conditioning', '', ''),
        row("Zanneti's", '5-8 rep range, 1-2 sets', 'conditioning', '', ''),
      ]),
      tab('Weak Day', [
        row('Warmup (Wrist warmup)', 'Rep range', 'warmup', '', ''),
        row('Max straddle hold', '2', 'volume / intensity', 'max straddle planche hold, aim for as perfect form as possible, PPT, toes pointed, i will show you how to enter with my strat.', ''),
        row('Max adv tuck hold', '2 sets', 'volume / intensity', 'Max straddle hold, dropsetted to max adv tuck hold. You can rest up to 5 seconds and catch your breathe between the holds', ''),
        row('2x banded straddle press', '2-3 rep range 2 sets', 'volume / intensity', 'alternate with below', ''),
        row('Banded Max straddle hold', '5-8 seconds, once you hit 8 seconds we will decrease band 3 sets', 'volume', 'alternate with above', ''),
        row('supinated adv tuck planche (Floor)', '2 sets', 'volume', 'good for height', ''),
        row('1-2 sets max p bar HSPU', 'max', 'conditioning', 'depending how tired you are', ''),
        row('weighted dip program', 'Rep range', 'conditioning', '', ''),
        row('Dolphin presses', 'not really specific rep range but just get familiar with the movement', 'conditioning', 'Engage super hard through serratus, same activations as pseudo lean but mostly focusing on the serratus, external rotation, chin, PPT, core', ''),
        row('Planche lean', 'not specific set, just get familiar with the movement and engagements', 'conditioning', 'Really work on the correct activations: PPT, engage core, chin slightly forward, press through serratus, externally rotate, breathing, pointed toes', ''),
        row('Planche presses', 'not specific set, just get familiar with the movement and engagements', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'LENNON184', student_name: 'Lennon',
    tabs: [
      tab('Push', [
        row('Warmup (Wrist warmup)', 'Set range', 'warmup', '', ''),
        row('bent arm press attempts', '2 sets, as many as you can do in one set', 'attempt', '', ''),
        row('Chest to wall handstand pushups max', '2 sets', 'volume / intensity', '', ''),
        row('Decline pike pushup max reps', '2 sets', 'volume / intensity', '', ''),
        row('Pike pushups max reps', '2 sets', 'volume / intensity', '', ''),
        row('Handstand holds', '2 sets, try to attempt even if you cant hold :)', 'conditioning', '', ''),
        row('Handstand chest to wall toe taps', '2 sets, as many as you can do in one set', 'conditioning', '', ''),
        row('Dips', 'Max reps x2 (Good form)', 'conditioning', '', ''),
        row('Scapular pushups to normal pushups', '10 reps 1 set', 'conditioning', '', ''),
      ]),
      tab('Pull', [
        row('Warmup', 'Rep Range', 'warmup', '', ''),
        row('Black + red banded FL max', '2 sets', 'volume / intensity', '', ''),
        row('Adv tuck FL max', '3 sets', 'volume / intensity', '', ''),
        row('Green +red band FL max', '2 sets', 'volume / intensity', '', ''),
        row('Green + black banded FL hip thrusts', '2 set', 'conditioning', '', ''),
        row('Green + black banded reverse deadlifts', '2 set', 'conditioning', '', ''),
        row('Max weighted pullups, a weight that allows u to do 3-5 rep range', '2 sets', 'conditioning', '', ''),
        row('Max high pullups', '2 sets', 'conditioning', 'Grease the groove', ''),
        row('Max pullups', 'Rep Range', 'conditioning', '', ''),
        row('L sit max', '1 set', 'conditioning', '', ''),
        row('Elevated L sit (P bars)', '2 sets', 'conditioning', '', ''),
        row('Tuck L sit (P bars)', '2 sets', 'conditioning', '', ''),
      ]),
    ],
  },
  {
    access_code: 'SEAN138', student_name: 'Sean',
    tabs: [],
  },
  {
    access_code: 'MATHEW154', student_name: 'Mathew',
    tabs: [],
  },
];