export const programs = [
  {
    id: 'handstand-free',
    name: 'Free Handstand Beginner Guide',
    emoji: '🤸',
    thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=400&fit=crop',
    tag: 'FREE',
    tagColor: 'text-green-400 bg-green-400/15',
    available: true,
    locked: false,
    for: 'Beginners with zero handstand experience',
    skill: 'Handstand',
    description: 'Learn to kick up, balance, and build your first freestanding handstand from scratch.',
    requirements: [],
    goals: ['First freestanding kick-up', 'Wall conditioning foundation', 'Balance entry technique'],
    includes: ['Wall conditioning drills', 'Kick-up technique', 'Balance progressions', 'Freestanding hold training'],
    to: '/tutorials/handstand',
    cta: 'Start Free',
  },
  {
    id: 'handstand-program',
    name: 'Handstand Program',
    emoji: '🤸‍♂️',
    thumbnail: 'https://images.unsplash.com/photo-1599058917765-a780eda07a3e?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-primary bg-primary/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with basic kick-up ability',
    skill: 'Handstand',
    description: 'Full structured 12-week handstand program from freestanding holds to HSPU and walking.',
    requirements: ['Basic kick-up ability', 'Some wall handstand experience'],
    goals: ['30+ second freestanding handstand', 'HSPU progressions', 'One-arm handstand prep'],
    includes: ['12-week periodized plan', 'Freestanding → HSPU pathway', 'Video breakdowns per phase', 'One-arm handstand prep'],
    to: '/purchase?type=handstand',
    cta: 'Get Access',
  },
  {
    id: 'planche-free',
    name: 'Free Planche Conditioning',
    emoji: '💪',
    thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop',
    tag: 'FREE',
    tagColor: 'text-green-400 bg-green-400/15',
    available: true,
    locked: false,
    for: 'Athletes building straight-arm strength',
    skill: 'Planche',
    description: 'Build the wrist, scapula, and straight-arm strength required for planche progressions.',
    requirements: [],
    goals: ['Wrist preparation complete', 'Scapula conditioning base', 'Planche lean foundation'],
    includes: ['Wrist preparation', 'Scapula conditioning', 'Pseudo planche pushups', 'Planche lean protocol'],
    to: '/tutorials/planche',
    cta: 'Start Free',
  },
  {
    id: 'planche-v1',
    name: 'Planche V1',
    emoji: '🏆',
    thumbnail: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-primary bg-primary/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with foundational pushing strength',
    skill: 'Planche',
    description: 'Build the tuck planche and develop the straight-arm strength and scapular control needed for all planche progressions.',
    requirements: ['~30 pushups', '10 dips', 'Foundational pushing strength'],
    goals: ['5 second advanced tuck planche', 'Stronger shoulder strength', 'Improved scapular control', 'Improved straight-arm strength'],
    includes: ['Tuck planche progressions', 'Planche lean protocol', 'Scapular strength training', 'Straight-arm conditioning', 'HSPU prep strength'],
    recommended: ['L-Sit to Handstand Program', 'HSPU Program'],
    bundleNote: 'Buy 2 programs and receive 20% off.',
    to: '/purchase?type=planche',
    cta: 'Get Access',
  },
  {
    id: 'planche-v2',
    name: 'Planche V2',
    emoji: '⚡',
    thumbnail: 'https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-primary bg-primary/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with advanced tuck planche',
    skill: 'Planche',
    description: 'Progress to straddle planche with HSPU strength integration. HSPU V2 is highly recommended — handstand pushups are heavily used in this phase.',
    requirements: ['5 second advanced tuck planche', 'Strong bent arm press or handstand pushup strength'],
    goals: ['5 second straddle planche', 'Multiple handstand pushups', 'Stronger shoulder endurance', 'Cleaner planche form'],
    includes: ['Straddle planche progressions', 'HSPU integration training', 'Shoulder endurance protocols', 'Form refinement drills'],
    recommended: ['HSPU V2 — highly recommended for this phase'],
    to: '/purchase?type=planche',
    cta: 'Get Access',
  },
  {
    id: 'planche-v3',
    name: 'Planche V3',
    emoji: '💎',
    thumbnail: 'https://images.unsplash.com/photo-1546519638405-a9f4cc66b87b?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-primary bg-primary/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 5 second clean straddle planche',
    skill: 'Planche',
    description: 'Build straddle planche endurance and develop the pressing strength needed to bridge toward full planche.',
    requirements: ['5 second clean straddle planche'],
    goals: ['Consistent 8+ second straddle hold', 'Deadstop straddle press', 'Controlled negatives', 'Straddle raises'],
    includes: ['Straddle endurance cycles', 'Deadstop press training', 'Negative planche protocol', 'Straddle raise progressions'],
    to: '/purchase?type=planche',
    cta: 'Get Access',
  },
  {
    id: 'planche-v4',
    name: 'Planche V4',
    emoji: '👑',
    thumbnail: 'https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-primary bg-primary/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 8+ second straddle planche',
    skill: 'Planche',
    description: 'Bridge from straddle to the full planche — the pinnacle of straight-arm pushing strength.',
    requirements: ['8+ second straddle planche', 'Deadstop straddle press', 'Straddle press negatives'],
    goals: ['5 second full planche', 'Stronger full planche consistency', 'Advanced planche control'],
    includes: ['Full planche transition work', 'Max effort full planche attempts', 'Advanced pressing cycles', 'Peak strength periodization'],
    to: '/purchase?type=planche',
    cta: 'Get Access',
  },
  {
    id: 'frontlever-v1',
    name: 'Front Lever V1',
    emoji: '⚡',
    thumbnail: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 5–10 pullups',
    skill: 'Front Lever',
    description: 'Build your tuck front lever and develop the horizontal pulling strength and lat activation needed for all FL progressions.',
    requirements: ['Minimum 5 pullups', 'Ideally 10 pullups'],
    goals: ['10 second tuck front lever', '3 second advanced tuck front lever'],
    includes: ['Tuck FL holds & progressions', 'Ice cream maker introduction', 'Lat activation protocols', 'Core horizontal strength'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-v2',
    name: 'Front Lever V2',
    emoji: '🔱',
    thumbnail: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 10 pullups and 3 sec adv tuck',
    skill: 'Front Lever',
    description: 'Develop advanced tuck endurance and begin purple band full front lever work.',
    requirements: ['10 pullups', '3 second advanced tuck front lever', 'Easy 10+ second tuck hold'],
    goals: ['Consistent 5+ second advanced tuck', '5 second purple band front lever', 'Improved front lever form'],
    includes: ['Advanced tuck FL endurance', 'Purple band FL progressions', 'Front lever rows', 'Scapular retraction strength'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-v3',
    name: 'Front Lever V3',
    emoji: '💎',
    thumbnail: 'https://images.unsplash.com/photo-1590487988256-9ed24133863e?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 5 sec adv tuck and 5 sec purple band FL',
    skill: 'Front Lever',
    description: 'Progress to black band and build serious full FL holding capacity.',
    requirements: ['Consistent 5+ second advanced tuck', '5 second purple band front lever'],
    goals: ['5 second black band front lever', '10+ second advanced tuck', '10+ second purple band hold'],
    includes: ['Black band FL progression', 'Advanced tuck to 10 sec', 'FL row volume building', 'Periodized pulling cycles'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-v4',
    name: 'Front Lever V4',
    emoji: '🏅',
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 5 sec black band and 10 sec adv tuck FL',
    skill: 'Front Lever',
    description: 'Transition to red band and build FL raises for full FL strength.',
    requirements: ['5 second black band front lever', '10+ second advanced tuck', '10+ second purple band'],
    goals: ['3–5 second red band front lever', '10+ second black band hold', '3+ black band raises'],
    includes: ['Red band FL progressions', '10 sec black band hold', 'Black band FL raises', 'Intensity periodization'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-v5',
    name: 'Front Lever V5',
    emoji: '🌟',
    thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 3–5 sec red band FL',
    skill: 'Front Lever',
    description: 'Build red band endurance and FL raises for full front lever development.',
    requirements: ['3–5 second red band front lever', '10 second black band front lever'],
    goals: ['10 second red band front lever', '3+ front lever raises'],
    includes: ['Red band hold endurance to 10 sec', 'FL raises introduction', 'Max effort FL attempts', 'Pulling strength cycles'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-v6',
    name: 'Front Lever V6',
    emoji: '👑',
    thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 10 sec red band FL',
    skill: 'Front Lever',
    description: 'Unlock the full front lever — the pinnacle of horizontal pulling strength.',
    requirements: ['10 second red band front lever'],
    goals: ['3–5 second full front lever', 'Easier red band raises'],
    includes: ['Full FL first attempts', 'Advanced FL raises', 'FL rowing variations', 'Peak strength cycles'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'frontlever-advanced-v6',
    name: 'Advanced Front Lever V6',
    emoji: '🔥',
    thumbnail: 'https://images.unsplash.com/photo-1507398941214-572c25f4b1dc?w=600&h=400&fit=crop',
    tag: 'PREMIUM',
    tagColor: 'text-cyan-400 bg-cyan-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 3–5 sec full front lever',
    skill: 'Front Lever',
    description: 'Elite front lever mastery — extend holds, build raises, and own the full front lever.',
    requirements: ['3–5 second full front lever', 'Strong front lever raises'],
    goals: ['8–10 second full front lever', '3+ full front lever raises'],
    includes: ['Full FL endurance cycles', 'Max raises protocol', 'Elite periodization', 'Peak performance programming'],
    to: '/purchase?type=frontlever',
    cta: 'View Program Details',
  },
  {
    id: 'muscleup-program',
    name: 'Muscle-Up Program',
    emoji: '💥',
    thumbnail: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop',
    tag: 'COMING SOON',
    tagColor: 'text-amber-400 bg-amber-400/15',
    available: false,
    locked: true,
    for: 'Athletes with 8+ clean pullups',
    skill: 'Muscle-Up',
    description: 'Go from high pullups to strict chest-to-bar and clean muscle-up repetitions.',
    requirements: ['8+ clean pullups'],
    goals: ['First strict muscle-up', 'Chest-to-bar pullups', 'Clean ring muscle-up'],
    includes: ['Transition skill training', 'False grip conditioning', 'Band-assisted progressions', 'Strict MU protocol'],
    to: '/purchase?type=coaching',
    cta: 'Apply for 1-on-1 Coaching',
  },
  {
    id: 'hspu-program',
    name: 'HSPU Program',
    emoji: '🎯',
    thumbnail: 'https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?w=600&h=400&fit=crop',
    tag: 'COMING SOON',
    tagColor: 'text-amber-400 bg-amber-400/15',
    available: false,
    locked: true,
    price: '$30',
    for: 'Athletes with 10+ second handstand holds',
    skill: 'HSPU',
    description: 'Progress from pike pushups and wall HSPU to freestanding handstand pushups.',
    requirements: ['10+ second handstand hold'],
    goals: ['Wall HSPU mastery', 'Freestanding HSPU', 'Bent arm press strength'],
    includes: ['Pike pushup protocol', 'Wall HSPU progressions', 'Bent arm press training', 'Freestanding HSPU pathway'],
    to: '/purchase?type=coaching',
    cta: 'Apply for 1-on-1 Coaching',
  },
  {
    id: 'coaching-1on1',
    name: '1-on-1 Coaching',
    emoji: '👁️',
    thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=400&fit=crop',
    tag: 'AVAILABLE NOW',
    tagColor: 'text-primary bg-primary/15',
    available: true,
    locked: false,
    featured: true,
    for: 'Serious athletes ready to fast-track results',
    skill: 'All Skills',
    description: 'Direct coaching from BTCALI. Custom programs, video feedback, and weekly strategy. The fastest path to elite calisthenics results.',
    requirements: [],
    goals: ['Personalized progression plan', 'Form corrections every session', 'Fastest possible results'],
    includes: ['Custom periodized program', 'Weekly video feedback', 'Direct coach messaging', 'Athlete progress tracking', 'Flexible skill focus'],
    to: '/purchase?type=coaching',
    cta: 'Apply for Coaching',
  },
];