export const tutorials = {
  handstand: {
    id: 'handstand',
    title: 'Free Handstand Beginner Guide',
    description: 'Master the fundamentals of handstand balance from complete beginner to your first hold.',
    thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=400&fit=crop',
    sections: [
      {
        id: 'bail_tutorial',
        title: 'Handstand Bail Tutorial',
        description: 'Learn to safely exit a handstand — the foundation of fearless kicking up.',
        videoUrl: 'https://youtube.com/shorts/rGoEHcIPeFY',
        isYouTube: true,
        steps: [
          'Learn the bunny hop bail — step over with one foot, rotate hips',
          'Coordinate hands staying planted as feet come down',
          'Gradually kick higher as bail confidence builds',
          'Rotate hips fully through — half cartwheel style exit',
          'Place one hand forward before feet land to guide rotation',
          'Look slightly in front of hands — not between them',
        ],
        keyNotes: [
          'Elevate and push shoulders into the floor hard',
          'Look slightly in front of your hands, not straight down',
          'Practise kick-ups often — fear disappears through repetition',
        ],
        commonMistakes: [
          'Fear of kicking up — leads to weak attempts and falls',
          'Not rotating hips during the bail',
          'Depressing shoulders instead of elevating them',
        ],
      },
      {
        id: 'kickup_tutorial',
        title: 'Handstand Kick-Up Tutorial',
        description: 'Master the entry — consistent kick-ups are the gateway to balance.',
        videoId: 'dQw4w9WgXcQ',
        steps: [
          'Set up in runners start position — dominant foot forward',
          'Drive back leg up first, let front leg follow',
          'Focus on getting feet above your head — not just high',
          'Do not be scared to kick harder — height = time to balance',
          'Use fingers to press and micro-adjust balance',
          'Squeeze glutes at the top — point toes for full body tension',
        ],
      },
      {
        id: 'wall_drills',
        title: 'Wall Drills & Toe Taps',
        description: 'Build overhead strength and body awareness with wall-supported handstand drills.',
        videoId: 'dQw4w9WgXcQ',
        steps: [
          'Chest-to-wall setup — body pressed flat against wall',
          'Activate shoulders: push floor hard, elevate not depress',
          'Squeeze glutes and engage PPT (posterior pelvic tilt)',
          'Point toes — creates full body tension throughout hold',
          'Alternating toe taps off wall — stay balanced between each',
          'Progress to removing both feet simultaneously',
        ],
      },
      {
        id: 'kickup_drills',
        title: 'Kick-Up Drills',
        description: 'Learn to safely and consistently kick up into a handstand.',
        videoId: 'dQw4w9WgXcQ',
        steps: ['Lunge kick-ups x 10 each leg', 'Scissor kick entries x 10', 'Light kick to balance x 5', 'Partner-assisted kick-ups x 5'],
      },
      {
        id: 'balance_drills',
        title: 'Balance Drills',
        description: 'Develop the fine motor control needed for freestanding handstand balance.',
        videoId: 'dQw4w9WgXcQ',
        steps: ['Finger pressure drills 30s x 3', 'Heel pull corrections x 10', 'Weight shifts side to side x 10', 'Single toe off wall x 5'],
      },
      {
        id: 'bent_arm_press',
        title: 'Bent Arm Press Tutorial',
        description: 'Build the pressing foundation for L-sit to handstand and HSPU.',
        videoUrl: 'https://www.youtube.com/watch?v=uMyv-LMlR0o',
        isYouTube: true,
        steps: [
          'Technique matters more than strength here — prioritize position',
          'Build foundational pike pushup strength first (3x10 minimum)',
          'Pike pushup → elevated pike → decline pike progression',
          'This is your direct pathway toward L-sit to handstand',
          'Wall HSPU attempts begin once pike pushups are strong',
          '1-on-1 coaching highly recommended — technique varies per athlete',
        ],
      },
      {
        id: 'holds',
        title: 'Handstand Holds',
        description: 'Progress your hold time with structured freestanding endurance training.',
        videoId: 'dQw4w9WgXcQ',
        steps: ['Max hold attempts x 5', 'Wall endurance 45s x 3', 'Kick-up and hold 5s x 10', 'Freestanding accumulation 2 min total'],
      },
    ],
    roadmap: [
      { name: 'Wall Holds', description: 'Build overhead endurance' },
      { name: 'Kick-Up Control', description: 'Consistent entry technique' },
      { name: 'Balance Development', description: 'Fine motor handstand control' },
      { name: 'Freestanding Hold', description: 'Independent handstand mastery' },
    ],
  },
  planche: {
    id: 'planche',
    title: 'Free Planche Conditioning',
    description: 'Build the foundational straight-arm strength and tendon conditioning for planche progression.',
    thumbnail: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop',
    sections: [
      {
        id: 'wrist_prep',
        title: 'Wrist Prep',
        description: 'Essential wrist conditioning to handle planche loading safely.',
        videoId: 'dQw4w9WgXcQ',
        steps: ['Wrist circles 20 each direction', 'Wrist flexion stretch 30s x 3', 'Wrist extension stretch 30s x 3', 'Knuckle pushups x 10'],
      },
      {
        id: 'scapula_strength',
        title: 'Scapula Strength',
        description: 'Develop the scapula protraction and depression needed for planche.',
        videoId: 'dQw4w9WgXcQ',
        steps: ['Scapula pushups x 15', 'Plank protraction holds 30s x 3', 'Scapula dips x 12', 'Band pull-aparts x 15'],
      },
      {
        id: 'pseudo_pushups',
        title: 'Pseudo Planche Pushups',
        description: 'The key exercise for building planche-specific pressing strength.',
        videoId: 'dQw4w9WgXcQ',
        steps: ['Hands by hips pushups x 8', 'Lean forward pushups x 8', 'Elevated pseudo pushups x 6', 'Isometric lean holds 15s x 3'],
      },
      {
        id: 'planche_leans',
        title: 'Planche Leans',
        description: 'Progressive leaning drills to build planche-specific loading.',
        videoId: 'dQw4w9WgXcQ',
        steps: ['Floor planche lean 15s x 5', 'Parallette leans 15s x 5', 'Band-assisted tuck planche x 5', 'Negative planche lowers x 3'],
      },
      {
        id: 'tendon_conditioning',
        title: 'Tendon Conditioning',
        description: 'Strengthen tendons and connective tissue for long-term planche training.',
        videoId: 'dQw4w9WgXcQ',
        steps: ['Isometric holds 20s x 4', 'Slow eccentric pushups x 6', 'Wrist roller x 3 sets', 'Rice bucket training 2 min'],
      },
    ],
    roadmap: [
      { name: 'Wrist & Tendon Foundation', description: 'Prepare connective tissue' },
      { name: 'Scapula Conditioning', description: 'Build protraction strength' },
      { name: 'Pseudo Planche Pushups', description: 'Develop lean pressing power' },
      { name: 'Planche Lean Mastery', description: 'Progressive loading' },
      { name: 'Tuck Planche Attempts', description: 'First planche position' },
    ],
  },
};